### ISSUE TITLE
Daikon does not detect the range of an int variable

### ISSUE THREAD

**Issue by nsendetsky** [codespecs/daikon#159]
Here is the system information:

Ubuntu 18.04.2 LTS

Java
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

 gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

kvasir
==14147== kvasir-5.7.2, C/C++ Language Front-End for Daikon with DynComp comparability analysis tool.
==14147== Copyright (C) 2007-2018, University of Washington CSE PLSE Group
==14147== Using Valgrind-3.13.0.Fjalar and LibVEX; rerun with -h for copyright info
==14147== Command: ./CopyString XI1AOi
==14147==
XI1AOi
==14147==
==14147== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

Daikon
Daikon version 5.7.2, released November 7, 2018; http://plse.cs.washington.edu/daikon.

Steps to reproduce.

1. Compile C source code - "gcc -gdwarf-2 -no-pie CopyString.c -o CopyString"
The program is very simple - just print a string received as an argument. Both the length of the string and the string itself are instrumented. There is other functionality in the program but it not used during instrumentation.

2. Run the "run_cs.py" python script. It creates a random string of length 6-10 and pass it to a bash scripts (run_cs.sh and run_cs_2.sh) that call kvasir instrumentation to capture traces

3. Run the following command to get Daikon output:
java -cp $DAIKONDIR/daikon.jar daikon.Daikon \
--config_option daikon.derive.Derivation.disable_derived_variables=true \
daikon-output/CopyString.decls daikon-output/CopyString.dtrace

Here is the Daikon output
> daikon-output/CopyString.decls daikon-output/CopyString.dtrace
Daikon version 5.7.2, released November 7, 2018; http://plse.cs.washington.edu/daikon.
(read 1 decls file)                                                            .
Processing trace data; reading 1 dtrace file:
[12:50:37 PM]: Finished reading daikon-output/CopyString.dtrace
===========================================================================
..bb():::ENTER
===========================================================================
..bb():::EXIT
===========================================================================
..ff():::ENTER
===========================================================================
..ff():::EXIT
===========================================================================
..main():::ENTER
argc == 2
argv != null
argv[] == [./CopyString]
argv[] elements == "./CopyString"
===========================================================================
..main():::EXIT
argv[] == [./CopyString]
argv[] elements == "./CopyString"
return == 0
Exiting Daikon.

When the range set to [6, 8] the output was valid.
Daikon version 5.7.2, released November 7, 2018; http://plse.cs.washington.edu/daikon.
(read 1 decls file)                                                            .
Processing trace data; reading 1 dtrace file:
[12:55:09 PM]: Finished reading daikon-output/CopyString.dtrace
===========================================================================
..bb():::ENTER
===========================================================================
..bb():::EXIT
===========================================================================
..ff():::ENTER
ln one of { 6, 7, 8 }
===========================================================================
..ff():::EXIT
===========================================================================
..main():::ENTER
argc == 2
argv != null
argv[] == [./CopyString]
argv[] elements == "./CopyString"
===========================================================================
..main():::EXIT
argv[] == [./CopyString]
argv[] elements == "./CopyString"
return == 0
Exiting Daikon.

Please find the source code, scripts, decl, dtrace files attached.

.decl and .dtrace for 100000 iteration can be provided. Please let me know if they or any additional information are needed.

**Comment by nsendetsky** [comment]
[daikon_bug_report.txt](https://github.com/codespecs/daikon/files/3067086/daikon_bug_report.txt)
[CopyString_decl_and_dtrace.zip](https://github.com/codespecs/daikon/files/3067087/CopyString_decl_and_dtrace.zip)
[CopyString_source_code_and_scripts.zip](https://github.com/codespecs/daikon/files/3067088/CopyString_source_code_and_scripts.zip)

**Comment by mernst** [comment]
Daikon only outputs "one of" invariants when the set of values is of size 3 or less.
You can increase the limit by setting the `daikon.inv.unary.sequence.EltOneOf.size` configuration option.  For example, if you set it to 5, Daikon's output ill include
```
ln one of { 6, 7, 8, 9, 10 }
```

This is documented in the [Daikon manual](http://plse.cs.washington.edu/daikon/download/doc/daikon.html#Invariant-list); search for " one of " (without the quotes) and it's the 5th match.
