### ISSUE TITLE
Improper usage of `com.sun` packages

### ISSUE THREAD

**Issue by MJafarMashhadi** [codespecs/daikon#208]
```
$ uname -a
Darwin MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

$ java -version
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

$ javac -version
javac 13.0.1
```

Compilation fails on `daikon/config/InvariantDoclet.java`, `daikon/config/ParameterDoclet.java`, and wherever you have imported `com.sun.javadoc` which is wrong.

According to [Oracle](https://www.oracle.com/java/technologies/faq-sun-packages.html): The sun.* packages are not part of the supported, public interface and their use is discouraged. I am trying to find a workaround for this issue. As of yet, I have not investigated the code thoroughly to see what purpose these files are exactly serving but the incompatibility issue seems serious and needs to be addressed.

**Comment by mernst** [comment]
As documented in the manual, Daikon runs on JDK 8. We are working to support JDK 11 and above.

**Comment by MJafarMashhadi** [comment]
I ended up installing a Java 8 anyways but "a Java 8 (or later)" and "In order to run Daikon, you must have a Java 8 (or later) JDK" straight from the docs + the commits that suppress the deprecation warnings make it confusing then.

**Comment by mernst** [comment]
You are right that the manual is incorrect!  I apologize for that.

This was recently discussed on the mailing list at https://groups.google.com/d/msg/daikon-discuss/3LFW9_3n0MM/i3hpE6EbBgAJ .  I have now updated the version of the manual on the web, but not the source in the source code repository.  We hope to support Java 11 this year, making the manual's text correct again.

Thanks for the bug report.

**Comment by MJafarMashhadi** [comment]
Thank you!
