### ISSUE TITLE
Documentation issue: min-length and max-length doc includes unhelpful note

### ISSUE THREAD

**Issue by mwchase** [codespecs/daikon#273]
The documentation for the [Variable declarations](http://plse.cs.washington.edu/daikon/download/doc/developer.html#Variable-declarations) fields of `min-length` and `max-length` includes the following note:

> Note that this item should be added to the `arrayname[..]` entry not the `arrayname[..]` entry.

According to the git history, this used to say something more like:

> Note that this item should be added to the `arrayname[..]` entry not the `arrayname[]` entry.

In any case, the current documentation is opaque to anyone who doesn't basically know what it's supposed to say already.

**Comment by mernst** [comment]
Thanks for pointing that out.  I agree the sentences are unhelpful, and I have deleted them.
