### ISSUE TITLE
More work needs to be done on splitter

### ISSUE THREAD

**Issue by mernst** [codespecs/daikon#35]
Originally reported on Google Code with ID 35
```
1) shadowing problems with class var and method var of same name
2) when need both class var and method var with some name don't generate unique names
3) daikon.test.spliter.SplitterFactorTestUpdatter needs to be corrected

```

Reported by `markro@cs.washington.edu` on 2014-10-27 22:34:07

**Comment by markro49** [comment]
commit 5460f4638e4a64364a0ef3b14c520f6df69db4e4
Author: Mark Roberts <markro@cs.washington.edu>
Date:   Fri Mar 11 10:58:08 2016 -0800

    Fix support for orig variables in splitters

this commit closes this issue
