### ISSUE TITLE
 Extend front ends to output more variable values

### ISSUE THREAD

**Issue by peikexin9** [codespecs/daikon#384]
According to https://plse.cs.washington.edu/daikon/download/doc/daikon.html#Loop-invariants, in order to infer loop invariant (e.g., for single function program), we can manually insert dummy method call by specifying variables of interest.
Is there any systematic way to extend existing front ends (Chicory and Kvasir) to output more values (e.g., local variables) without manually specifying them? Any reference would be greatly appreciated.

**Comment by peikexin9** [comment]
Thanks @mernst! I am still following the workaround by using dummy call insertions, but automating it with AST parser. I will try to contribute that part at some point if that's useful.

**Comment by mernst** [comment]
That sounds great.  Thank you.
