### ISSUE TITLE
Minor user manual (documentation) issues

### ISSUE THREAD

**Issue by sharkov63** [codespecs/daikon#392]
1. Seems that in [3.2.1](http://plse.cs.washington.edu/daikon/download/doc/daikon.html#Detecting-invariants-in-C_002fC_002b_002b-programs) in step 4 in the end of 2nd and 3rd code snippets we have uncomplete daikon run command:
```sh
java -Xmx3600m daikon.Daikon daikon-output/wordplay*.dtrace daikon-output/wordplay.decls
```
Should be
```sh
java $DAIKONDIR/daikon.jar -Xmx3600m daikon.Daikon daikon-output/wordplay*.dtrace daikon-output/wordplay.decls
```

2. Typo in [5.1](http://plse.cs.washington.edu/daikon/download/doc/daikon.html#Invariant-syntax) in JML format: instead of `Produces output in JVM` should be `Produces output in JML`.

**Comment by mernst** [comment]
Thanks very much for noticing these typos (and our apologies for letting them slip in).

I fixed them in https://github.com/codespecs/daikon/commit/87a69a728677d5702055f8a1b6c17cfebbb23907 .
