### ISSUE TITLE
DynComp does not work for command line inputs

### ISSUE THREAD

**Issue by peikexin9** [codespecs/daikon#399]
I noticed when feeding java programs that accept command line input, e.g., Scanner s = new Scanner(System.in), to daikon.DynComp, it hangs without accepting the input and never terminates. It can be terminated by Ctrl+C, but the generated .decl files do not have correct variable comparability value, i.e., all variables are marked not comparable with different numbers.

**Comment by mernst** [comment]
Thanks for the bug report. I'm sorry you are having trouble.

As requested in the issue template, can you please provide a reproduction? Otherwise we will waste time trying to reproduce the problem and any fix might not address your needs. Thanks.

**Comment by peikexin9** [comment]
Thanks for the reply. I figured it is because DynComp does not redirect the stdin. Adding
```
StreamRedirectThread stdin_thread = new StreamRedirectThread("stdin", System.in, dcomp_proc.getOutputStream(), false);
stdin_thread.start();
```
before https://github.com/codespecs/daikon/blob/31a00f8bf004527f18a1a49d8a28cbc4dad4135b/java/daikon/DynComp.java#L369 and recompile Daikon, resolves the problem.

**Comment by mernst** [comment]
Thanks for pointing out the problem; I really appreciate it.  I have fixed it in a slightly different way, in pull request #410.
