### ISSUE TITLE
Rename command-line arguments for DynComp for C

### ISSUE THREAD

**Issue by mernst** [codespecs/daikon#43]
DynComp for C's command-line argument names are inconsistently named.
I propose the following renamings.

--gc-num-tags => --dyncomp-gc-num-tags

--no-dyncomp-gc => --dyncomp-gc-num-tags=0

--dyncomp-fast-mode => --dyncomp-approximate-literals

--separate-entry-exit-comp => --dyncomp-separate-entry-exit

--dyncomp-dataflow-only => --dyncomp-interactions=none
--dyncomp-dataflow-comp => --dyncomp-interactions=comparisons
--dyncomp-units => --dyncomp-dataflow=units
[does not exist; is the default] => --dyncomp-dataflow=all

**Comment by markro49** [comment]
https://github.com/codespecs/fjalar/pull/17

completes this item
