### ISSUE TITLE
Dead code in addInvokeToClinit

### ISSUE THREAD

**Issue by mernst** [codespecs/daikon#54]
Chicory's method `Instrument.addInvokeToClinit` calls `call_initNotify`.  However, the call to `call_initNotify` looks like dead code, and it looks like it has been dead code since it was added in 2005.  What is `addInvokeToClinit` really trying to do?  Should we remove the call, or should we use its result?

Also in method addInvokeToClinit, the line
```
        InstructionList newList = mg.getInstructionList();
```
looks extraneous too.

**Comment by markro49** [comment]
I have never worked on this code - but it does seem weird to be calling a runtime method directly that is also called from instrumented code.

As for the newList = mg.getInstructionList();  This appears to be used at the end of the method to restore the instruction list to the original?  Which also seems weird.  Just want side effects from doing the instrumentation?  

Can't really explain - but I could put further investigation on my todo list if you wish.

**Comment by mernst** [comment]
Cleaning up or deleting this code isn't urgent, but it would improve code quality and is worth doing when there is time.

**Comment by markro49** [comment]
https://github.com/codespecs/daikon/commit/4826ad737e1966776685b80b825dc63f2353ffdf closes this issue.
