### ISSUE TITLE
Instructions for rebuilding Daikon with C/C++ front end results in error due to missing "etags" program

### ISSUE THREAD

**Issue by rcook** [codespecs/daikon#66]
Repro steps (following steps in Daikon User Manual "2.2.2 Unix/Linux/MacOSX installation" at https://github.com/codespecs/daikon/blob/master/doc/daikon.texinfo#L406):

- Download and extract `daikon-5.3.8.tar.gz` package into directory
- Set `DAIKONDIR` and `JAVA_HOME` environment variables
- Source `scripts/daikon.bashrc`
- Run following `make` command:

```bash
make -C $DAIKONDIR rebuild-everything
```

Make fails due to missing `etags` program with following output:

```text
make: Entering directory `/home/rcook/daikon-5.3.8'
make -C /home/rcook/daikon-5.3.8 rebuild-everything-but-kvasir
make[1]: Entering directory `/home/rcook/daikon-5.3.8'
make -C /home/rcook/daikon-5.3.8/java tags compile
make[2]: Entering directory `/home/rcook/daikon-5.3.8/java'
Makefile:749: *** etags is not available, please install it.  Stop.
make[2]: Leaving directory `/home/rcook/daikon-5.3.8/java'
make[1]: *** [rebuild-everything-but-kvasir] Error 2
make[1]: Leaving directory `/home/rcook/daikon-5.3.8'
make: *** [rebuild-everything] Error 2
make: Leaving directory `/home/rcook/daikon-5.3.8'
```

See https://github.com/codespecs/daikon/blob/master/java/Makefile#L749. This reproduces on my Centos 7 machine.

I'm guessing that `etags` is an Emacs-related program. I am not an Emacs user so I don't have it. Is there a straightforward way to install this program? Is this dependency on Emacs intentional? Perhaps the documentation should be updated to explain this step.

**Comment by mernst** [comment]
Thanks for pointing this out, Richard.  I have fixed it as you suggested.
I agree that it shouldn't be required that users have etags installed.  The previous step was convenient for Emacs users, but they can run "make tags" themselves.
