### ISSUE TITLE
kvasir invalid pointer in debug info

### ISSUE THREAD

**Issue by vucinic** [codespecs/daikon#79]
I built a program with Dwarf symbols. 
It includes third party libraries that I recompiled with Dwarf symbols.

I try to run kvasir on it and it produces a never ending execution that continuously outputs this:

`
dwarf.c: Warning: Invalid pointer size (-572662307) in debug info for entry 5
`

**Comment by mernst** [comment]
I'm sorry you are having trouble.  Without more information, we cannot reproduce your error, nor can we diagnose and fix it.

Can you give us a reproducible test case so that we can reproduce the problem?

**Comment by vucinic** [comment]
1. Got the latest version of Kvasir and build it as specified (https://plse.cs.washington.edu/daikon/download/doc/daikon/Front-ends-_0028instrumentation_0029.html#Installing-Kvasir)

2. Tried to run the wordplay example and everything worked fine

3. Tried the (provided) bzip2 example and Kvasir got stuck.

### Details
- Bzip has  been built with the following command
 ``
gcc -g -gdwarf-2 -o bzip bzip2.c
``

- The obtained `bzip` binary works fine with the attached '[small.txt](https://github.com/codespecs/daikon/files/595584/small.txt)' file, command
 ``
./bzip -k -z small.txt
``

- Kvasir has been launched as `kvasir-dtrace --verbose ./bzip -k -z small.txt &>verbose.txt` and the output is always the same, reported in '[verbose.txt](https://github.com/codespecs/daikon/files/595583/verbose.txt)'. Kvasir got stuck after:

``
--23929-- REDIR: 0x4ec9800 (libc.so.6:__GI_mempcpy) redirected to 0x4c35951 (__GI_mempcpy)
``

- Kvasir has been lauched as `kvasir-dtrace --verbose --kvasir-debug ./bzip -k -z small.txt &>verbose_debug.txt`, it got stuck and after more or less one minute the verbose_debug.txt file was 32MB large (not attached, but I will if it is needed).

Thanks

**Comment by markro49** [comment]
I think you just need a little more patience.  It's a compute intensive program.  Your example ran fine for me but took 5-6 minutes.

**Comment by mernst** [comment]
Maybe the manual should say how long to wait?
