### ISSUE TITLE
daikon.Chicory instrumentation can introduce ConcurrentModificationExceptions

### ISSUE THREAD

**Issue by Thiez** [codespecs/daikon#82]
While using Daikon in combination with EvoSuite I ran into a situation where the automatically generated tests would pass when I ran them normally, but would fail when I used Daikon. It turns out the generated test was attempting to trigger a `ConcurrentModificationException`, but it failed because the exception was not triggered in my code, but in daikon's instrumentation code. It was  trigged in daikon.chicory.ListInfo.getMyValFromParentFile, line 44, where `toArray` is called, and occurs when a list that has been concurrently modified is either passed as a method parameter, or is the parameter of a method that causes it to get into the "concurrently modified" state during the execution of that method. Here is a minimal program that demonstrates the problem for the former situation:

```java
public class Bug {
    public static void main(String[] args) {
        java.util.List<Object> base = new java.util.ArrayList<>();
        java.util.List<Object> bomb = base.subList(0, 0);
        base.add("");
        detonate(bomb);
    }
    public static void detonate(java.util.List<Object> bomb) {
    }
}
```

When compiled and run (`javac Bug.java && java Bug`) this program will print nothing and exit normally. When run with daikon (`javac Bug.java && java -cp .:path/to/daikon.jar daikon.Chicory Bug`), the result is:

```
entered daikon.chicory.Runtime.setDtrace(./Bug.dtrace.gz, false)...
Exception in thread "main" java.lang.Error: java.lang.reflect.InvocationTargetException
	at daikon.chicory.ListInfo.getMyValFromParentVal(ListInfo.java:50)
	at daikon.chicory.DTraceWriter.traverseValue(DTraceWriter.java:240)
	at daikon.chicory.DTraceWriter.traverse(DTraceWriter.java:212)
	at daikon.chicory.DTraceWriter.methodEntry(DTraceWriter.java:86)
	at daikon.chicory.Runtime.enter(Runtime.java:263)
	at Bug.detonate(Bug.java:8)
	at Bug.main(Bug.java:6)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at daikon.chicory.ListInfo.getMyValFromParentVal(ListInfo.java:44)
	... 6 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1231)
	at java.util.ArrayList$SubList.size(ArrayList.java:1040)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
	... 11 more
Warning: Target exited with 1 status
```

Similarly, we can do the following, where the exception is triggered when we leave `detonate`.

```java
public class Bug {
    public static void main(String[] args) {
        java.util.List<Object> base = new java.util.ArrayList<>();
        detonate(base.subList(0, 0), base);
    }
    public static void detonate(java.util.List<Object> bomb, java.util.List<Object> trigger) {
        trigger.add(new Object());
    }
}
```

I'm not sure what the best behavior would be in this instance, but perhaps some special casing for `java.util.SubList<T>` would be possible? I suppose this is but an instance of a much more general challenge, that daikon can trigger unintended execution of arbitrary code, e.g. the following code prints "Hello world" twice when run through daikon.Chicory, otherwise it prints nothing.

```java
public class Bug extends java.util.ArrayList<Object> {
    public static void main(String[] args) {
        runToArray(new Bug());
    }
    public static void runToArray(java.util.List<Object> bug) {}
    public Object[] toArray() {
        System.out.println("Hello world");
        return new Object[0];
    }
}
```

Of course the above code is probably not very realistic, but I think it would be nice if the sublist-problem could be solved.

**Comment by markro49** [comment]
My understanding is that modifying the base list while a subList is active is illegal – but, sensibly, Java does not throw an exception until the subList is subsequently used.  Thus these sample programs exit without error.  However, Daikon, it the process of ‘doing its job’ does inspect all variables at the entry and exit of a method and thus, the subList it viewed and this causes the exception to be thrown.
 
As you suggest, not sure what the appropriate behavior is here – but we will investigate.
 
Thank you,
Mark Roberts

**Comment by mernst** [comment]
Thanks for the investigation you have done and the detailed, useful test cases.
It's an interesting issue.

Daikon generalizes over run-time values, and uses a front end to observe those values.
One of the things the front end does in order to observe values is to call pure methods.
Calling a pure method has no side effects and doesn't affect the program's operation.

You have observed that there are methods that ought to be pure, but that behave impurely in some situations.
`toArray()` is one such example, but a front end also calls  others such as `toString()` and `hashCode()`.

The generated test that you showed makes assumptions about no pure methods being called, and therefore it's not compatible with Daikon's standard data observation.

We could solve your problem by adding a new argument to Daikon that disables calling any methods in the client code.  This would degrade Daikon's output, because Daikon would be given less information to generalize from, but it would enable Daikon to be run over brittle code like the test cases that you gave.

The call to `toArray' that is causing you trouble is in `ListInfo.getMyValFromParentVal()`.
`ListInfo` is instantiated only in `checkForListDecl`.
Again, note that calls to other methods would also need to be handled -- not just lists.

Thanks for raising the issue!

**Comment by markro49** [comment]
I have tested and checked in a fix for the specific problem of a ConcurrentModificationException when Chicory attempts to get the current contents of a subList.  The changes are in java/daikon/chicory/ListInfo.java. Your sample program now runs correctly.  Of course, this does not address the general case as Michael discusses above.  This change is not in the current release, but you may get the latest sources from this repository and build an updated version.

**Comment by Thiez** [comment]
I just noticed I forgot to respond to this issue! I've been using daikon with your fix of the `ConcurrentModificationException` problem and so far it's been working flawlessly. Thank you very much for the fix! Would you like for me to keep the issue open as a reminder of the more general problem (which probably affects almost nobody), or shall I close it?

**Comment by mernst** [comment]
Let's close this issue and open a new one for the general case.
